import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { cn } from "~/lib/utils";
import AuthProvider from "~/providers/auth";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <Toaster />
        <main className="min-h-screen flex flex-col justify-center items-center">
          <AuthProvider>{children}</AuthProvider>
        </main>
      </body>
    </html>
  );
}
